### ISSUE TITLE
Feature request: `put_multipart()` should accept `AsyncIterable[bytes]`

### ISSUE THREAD

**Issue by barneygale** [aiokitchen/aiohttp-s3-client#13]
`put_multipart()` currently accepts `Iterable[bytes]` for its *data* argument.

It would be lovely if it also accepted `AsyncIterable[bytes]`, like `put()` does. This would let me proxy a file upload (from an aiohttp server) to S3 without it needing to load it into memory or save it to a disk.

Thanks!

**Comment by dizballanze** [comment]
Hello.
I don't think that aiohttp provides `AsyncIterable` for a file upload.
In order to read file in chunks you need to use multipart reader and [`read_chunk`](https://docs.aiohttp.org/en/stable/multipart_reference.html#aiohttp.BodyPartReader.read_chunk) method of a part.
I think I will add support for `AsyncIterable`, but you still need to write code for handling multipart uploads and reading chunks of at least 5MB in size (besides the last one).

**Comment by barneygale** [comment]
Hey, I found another solution to this! No need to implement this feature just for me, please close if you wish.
